// Polish texts of the Medirian Client website, by data-t key (English is in index.html).
// Loaded only when the page is shown in Polish. scripts/build-website.mjs checks that every key exists.
window.MEDIRIAN_PL = {
  'meta.title': 'Medirian Client — klient i launcher Minecrafta',

  'nav.skip': 'Przejdź do treści',
  'nav.home': 'Start',
  'nav.features': 'Funkcje',
  'nav.mods': 'Mody',
  'nav.download': 'Pobierz',
  'nav.faq': 'FAQ',
  'nav.cta': 'Pobierz',
  'nav.menu': 'Menu',

  'hero.lead': 'Nowoczesny klient Minecrafta stworzony z myślą o wydajności, personalizacji i lepszej grze.',
  'hero.download': 'Pobierz dla Windows',
  'hero.explore': 'Poznaj funkcje',
  'hero.latest': 'Najnowsza wersja',
  'hero.meta': 'Windows 10/11 · Minecraft 1.8.9, 1.21.8, 1.21.11 i 26.3',

  'features.eyebrow': 'Launcher + klient',
  'features.title': 'Wszystko, czego potrzebujesz.',
  'features.lead': 'Medirian sam instaluje Minecrafta i Javę, a potem uruchamia grę z własnymi menu, modułami i HUD-em. Jedno pobranie, nic do ustawiania ręcznie.',
  'f.perf.t': 'Wydajność',
  'f.perf.d': 'Culling bytów, Dynamic FPS, kontrola cząsteczek i osobne dystanse rysowania pomagają utrzymać płynną grę.',
  'f.hud.t': 'HUD',
  'f.hud.d': 'W pełni konfigurowalny HUD z niezależnych widżetów — każdy przesuniesz, przyciągniesz i przeskalujesz w edytorze HUD.',
  'f.menu.t': 'Mod Menu',
  'f.menu.d': 'Własne menu Mediriana dla 41 modułów: kategorie, wyszukiwarka i lampka, która włącza i wyłącza każdy z nich.',
  'f.mods.t': 'Mody',
  'f.mods.d': 'Szukaj w Modrinth i instaluj mody prosto z launchera, razem z modami, których potrzebują.',
  'f.profiles.t': 'Profile',
  'f.profiles.d': 'Osobne profile, które nigdy się nie mieszają. Udostępnij profil jako kod i zaimportuj cudzy w kilka sekund.',
  'f.cosmetics.t': 'Kosmetyki',
  'f.cosmetics.d': 'Peleryny, czapki, skrzydła, ślady i emotki — i Twój własny skin Minecrafta w launcherze i w menu głównym.',
  'f.advanced.t': 'Ustawienia zaawansowane',
  'f.advanced.d': 'Grafika, renderowanie, widoczność, wydajność i interfejs w jednym miejscu. Każda opcja mówi, co robi.',
  'f.versions.t': 'Wiele wersji Minecrafta',
  'f.versions.d': '1.8.9, 1.21.8, 1.21.11 i 26.3 z tymi samymi modułami, HUD-em i kosmetykami. Java instaluje się sama.',

  'shots.eyebrow': 'Zrzuty ekranu',
  'shots.title': 'Zobacz sam.',
  'shots.lead': 'Prawdziwe ekrany z Medirian Client 0.4.0 — launcher i gra, nic nie jest dorysowane.',
  'shots.launcher.t': 'Launcher',
  'shots.launcher.d': 'Launcher. Każdy profil uruchamia jedną wersję Minecrafta z własną pamięcią, Javą i konfiguracją Mediriana.',
  'shots.menu.t': 'Menu główne',
  'shots.menu.d': 'Własne menu główne Mediriana w grze: spokojna noc przy chatce, a na ścieżce Twój skin.',
  'shots.modmenu.t': 'Mod Menu',
  'shots.modmenu.d': 'Mod Menu (prawy Shift). Każdy moduł ma własną ikonę i lampkę ON/OFF; kliknij kafelek, by zobaczyć jego ustawienia.',
  'shots.settings.t': 'Ustawienia',
  'shots.settings.d': 'Ustawienia w grze: Ogólne, HUD, Zaawansowane, Wydajność, Profile i konto Medirian.',
  'shots.cosmetics.t': 'Kosmetyki',
  'shots.cosmetics.d': 'Kosmetyki: peleryny, czapki, skrzydła, ślady i emotki na jednym ekranie.',

  'mods.eyebrow': 'Mody z Modrinth',
  'mods.title': 'Twoje mody. Po Twojemu.',
  'mods.lead': 'Zakładka Mody w launcherze przeszukuje Modrinth i instaluje mod do wybranego profilu — razem z modami, których wymaga. Medirian najpierw sprawdza wersję Minecrafta i loader, a gdy mod nie pasuje, mówi o tym wprost.',
  'mods.l1': 'Mody Fabric, a dla 1.8.9 mody Legacy Fabric',
  'mods.l2': 'Wymagane zależności instalują się razem z modem',
  'mods.l3': 'Wyłącz mod, zaktualizuj go albo usuń',
  'mods.l4': 'Mody zostają w swoim profilu',
  'mods.note': 'Medirian korzysta tylko z Modrinth — mody pobierają się prosto z Modrinth, przez jego oficjalne API.',
  'mods.browse': 'Przeglądaj mody na Modrinth',
  'mods.s1': 'Szukaj w Modrinth',
  'mods.s2': 'Wybierz mod',
  'mods.s3': 'Zainstaluj do profilu',
  'mods.s4': 'Uruchom Minecrafta',

  'profiles.eyebrow': 'Profile',
  'profiles.title': 'Jeden klient. Wiele zestawów.',
  'profiles.lead': 'Profil to jeden sposób gry: wersja Minecrafta z własną pamięcią, Javą i folderem gry, uruchamiana z wybraną konfiguracją Mediriana. Mody, ustawienia i światy jednego profilu nigdy nie trafiają do innego.',
  'profiles.own': 'Każdy profil może mieć własne',
  'profiles.c1': 'Moduły',
  'profiles.c2': 'HUD',
  'profiles.c3': 'Ustawienia',
  'profiles.c4': 'Mody',
  'profiles.c5': 'Konfigurację',
  'profiles.example': 'Przykładowe zestawy',
  'profiles.config': 'Konfiguracja:',
  'profiles.share.t': 'Udostępnij profil kodem',
  'profiles.share.d': 'Profile → Udostępnij tworzy kod z wersją, pamięcią, modułami, HUD-em i ustawieniami grafiki profilu. Importuj kod pokazuje zawartość, zanim go dodasz. Kod nigdy nie zawiera konta, tokenów, haseł ani ustawień Javy i wygasa po 90 dniach.',

  'hud.eyebrow': 'HUD',
  'hud.title': 'Małe widżety. Dokładnie tam, gdzie chcesz.',
  'hud.lead': 'Każdy moduł HUD to osobny widżet: przesuń go, przyciągnij do linii pomocniczych i przeskaluj w edytorze HUD. Wybierz wygląd — Liquid Glass z delikatnym rozmyciem świata pod spodem albo Klasyczny.',
  'hud.session': 'Sesja',
  'hud.classic': 'Klasyczny',
  'hud.illustration': 'Ilustracja — liczby są przykładowe.',

  'adv.eyebrow': 'Ustawienia zaawansowane',
  'adv.title': 'Dopracuj wszystko.',
  'adv.lead': 'Ustawienia → Zaawansowane łączą opcje samego Minecrafta z opcjami Mediriana w pięciu sekcjach. Zmieniają się dokładnie tak jak w ekranach opcji Minecrafta, widać tylko te, które ma Twoja wersja, a każda opisuje, co robi.',
  'adv.lead2': 'Gracze, byty, upuszczone przedmioty, cząsteczki, nicki i kosmetyki mogą przestać się rysować dalej niż wybrany dystans, a mgłę odległości można odsunąć albo wyłączyć.',
  'adv.graphics': 'Grafika',
  'adv.rendering': 'Renderowanie',
  'adv.visibility': 'Widoczność',
  'adv.performance': 'Wydajność',
  'adv.interface': 'Interfejs',
  'adv.illustration': 'Ilustracja ekranu Ustawienia → Zaawansowane; wartości są przykładowe.',

  'cos.eyebrow': 'Kosmetyki',
  'cos.title': 'Po swojemu.',
  'cos.lead': 'Wybierz pelerynę, czapkę, skrzydła, ślad i emotki na ekranie Kosmetyki. Inni gracze Mediriana widzą je, gdy jesteś zalogowany do usług Medirian, a czapka chowa się, gdy nosisz hełm.',
  'cos.capes': 'peleryn',
  'cos.hats': 'czapki',
  'cos.wings': 'pary skrzydeł',
  'cos.trails': 'ślady',
  'cos.emotes': 'emotki',
  'cos.skin': 'Twój własny skin Minecrafta widać w launcherze i w menu głównym gry.',
  'cos.try': 'Przymierz pelerynę:',

  'why.title': 'Zbudowany inaczej.',
  'why.1.t': 'Nastawiony na wydajność',
  'why.1.d': 'Culling, Dynamic FPS i osobne dystanse rysowania są wbudowane, a nie doklejone.',
  'why.2.t': 'Mocno konfigurowalny',
  'why.2.d': '41 modułów, każdy z własnymi ustawieniami i klawiszami.',
  'why.3.t': 'Wbudowane zarządzanie modami',
  'why.3.d': 'Wyszukiwanie w Modrinth, zależności i aktualizacje prosto w launcherze.',
  'why.4.t': 'Własny HUD',
  'why.4.d': 'Osobne widżety w stylu Liquid Glass albo Klasycznym, dokładnie tam, gdzie chcesz.',
  'why.5.t': 'Profile',
  'why.5.d': 'Zestawy, które się nie mieszają, i krótki kod, by się nimi podzielić.',
  'why.6.t': 'Przytulny pixel art',
  'why.6.d': 'Noc Halloween przez cały rok, w launcherze i w grze.',
  'why.7.t': 'Regularne aktualizacje',
  'why.7.d': 'Launcher i klient aktualizują się same; profile i światy zostają na miejscu.',

  'dl.title': 'Pobierz Medirian Client',
  'dl.lead': 'Jeden instalator. Instaluje launcher dla Twojego użytkownika Windows — bez uprawnień administratora — a launcher sam aktualizuje siebie i klienta.',
  'dl.button': 'Pobierz instalator',
  'dl.version': 'Wersja',
  'dl.released': 'Wydana',
  'dl.s1': 'Pobierz <b>MedirianClientSetup.exe</b>.',
  'dl.s2': 'Uruchom go. Medirian Client zainstaluje się dla Twojego użytkownika Windows, ze skrótami na pulpicie i w menu Start.',
  'dl.s3': 'Otwórz Medirian Client, zaloguj się kontem Microsoft i kliknij Graj. Minecraft i Java zainstalują się same.',
  'status.name': 'Usługi Medirian',

  'faq.title': 'Pytania',
  'faq.1.q': 'Czym jest Medirian Client?',
  'faq.1.a': 'Launcherem i klientem Minecrafta w jednym. Launcher instaluje Minecrafta i Javę, przechowuje Twoje profile i mody, i uruchamia grę z Medirianem: własnym menu głównym, Mod Menu, 41 modułami, konfigurowalnym HUD-em i kosmetykami.',
  'faq.2.q': 'Które wersje Minecrafta są obsługiwane?',
  'faq.2.a': 'Minecraft: Java Edition 1.8.9 (na Legacy Fabric), 1.21.8, 1.21.11 i 26.3 (na Fabric). Wszystkie cztery mają te same moduły, HUD i kosmetyki.',
  'faq.3.q': 'Czy Medirian jest darmowy?',
  'faq.3.a': 'Tak. Pobranie i gra z Medirianem nic nie kosztują i w launcherze ani w grze nie ma nic do kupienia. Potrzebujesz własnej kopii Minecraft: Java Edition.',
  'faq.4.q': 'Jak zainstalować Mediriana?',
  'faq.4.a': 'Pobierz <b>MedirianClientSetup.exe</b> i uruchom go — bez uprawnień administratora. Potem otwórz Medirian Client, zaloguj się kontem Microsoft i kliknij Graj. Odinstalujesz go jak każdą inną aplikację w Ustawieniach → Aplikacje; profile i światy zostają.',
  'faq.5.q': 'Czy mogę instalować mody?',
  'faq.5.a': 'Tak — w zakładce Mody w launcherze, do wybranego profilu. Medirian instaluje mody, których wymaga dany mod, sprawdza, czy pasuje do Twojej wersji Minecrafta i loadera, i pozwala mody wyłączać, aktualizować i usuwać.',
  'faq.6.q': 'Skąd pochodzą mody?',
  'faq.6.a': 'Z <a href="https://modrinth.com/mods" rel="noopener">Modrinth</a>, przez jego oficjalne API. Medirian nie hostuje modów sam i nie korzysta z CurseForge.',
  'faq.7.q': 'Czy mogę importować profile?',
  'faq.7.a': 'Tak. Profile → Importuj kod przyjmuje kod taki jak <code>MDN-7K4X-92QP-L8F2</code>, utworzony przez Udostępnij, pokazuje zawartość profilu i pyta, zanim cokolwiek zastąpi. Kody są ważne 90 dni. Konfiguracje Mediriana można też trzymać w Medirian Cloud (Ustawienia → Profile w grze).',
  'faq.8.q': 'Czy Medirian wymaga konta Microsoft?',
  'faq.8.a': 'Tak. Logujesz się kontem Microsoft, które ma Minecraft: Java Edition, na stronie logowania Microsoftu — Medirian nigdy nie widzi Twojego hasła.',
  'faq.9.q': 'Czy Medirian jest dostępny na macOS lub Linuxie?',
  'faq.9.a': 'Najpierw Windows 10 i 11: na nich Medirian jest budowany i testowany. Launcher powstaje też dla macOS i Linuxa; gdy wydanie zawiera te wersje, znajdziesz je w sekcji Pobierz powyżej.',

  'foot.download': 'Pobierz',
  'foot.privacy': 'Prywatność',
  'foot.terms': 'Regulamin',
  'foot.legal': 'Nie jest oficjalnym produktem Minecraft. Nie jest zatwierdzony przez Mojang ani Microsoft ani z nimi powiązany.'
};
